### PR TITLE
Implement use of NSEA points and time-axis in gridded output 

### PR DESCRIPTION
**Pull request by DeniseWorthen**
### Description of changes:

- Updates wave cap to use VMALLReduce across nsea points instead of nx*ny global points. 
- Adds FillGlobalInput interface to replace repeated code blocks in wav_import_export
- Replaces 25 1-d wave_elevation_spectrum fields and pointers with a single 2-d field and pointer
- Adds a time-axis to fields in the netCDF gridded output files. 
- Updates non-cap code with latest ufs-weather-model branch of NOAA-EMC

### Testing:

Test case/suite: SMS_Ld2.TL319_t061_wt061.GMOM_JRA_WD.cheyenne_intel
Test status: bit for bit 
There is also no performance degradation with this PR.

Fixes: None
User interface (namelist or namelist defaults) changes? No

### CODE REVIEW

**Comment by mvertens** [comment]
@alperaltuntas - I have been working closely with Denise on this PR. I have verified that results are bfb and that there is no longer any performance degradation.

**Comment by alperaltuntas** [comment]
@mvertens, I just ran a 1-year case to assess the performance. I am still getting ~4.5 model years per day. Prior to switching from v.6.14 (dev/ncar) to v.7 (dev unified), I was getting close to 7 model years per day. Are these performance numbers consistent with what you have observed?

**Comment by mvertens** [comment]
@alperaltuntas @DeniseWorthen - that's really discouraging. I actually did not do a performance analysis of dev/ncar versus dev/unified. I should have done that. Sorry! I only did a performance analysis of the latest PR from denise in dev/unified relative to the previous version. I'm not sure what to do right now. This is a bit of a show stopper in my opinion. Should we briefly meet to discuss the best path forwards?

**Comment by mvertens** [comment]
@alperaltuntas - have you verified that the dev/unified before this PR also ran at 4.5 model years per day? Or is it just the new PR.

**Comment by alperaltuntas** [comment]
Yes, dev/unified before this PR also ran at 4.5 model years per day.

**Comment by alperaltuntas** [comment]
Having said that, I wonder if it's due to the decreased timesteps. I think I checked that earlier and concluded that the performance degradation wasn't solely due to the decreased timesteps, but I am double-checking that now.

**Comment by mvertens** [comment]
@alperaltuntas - do you have any update on the performance slowdown? Is dev/unified itself a significant performance slowdown?

**Comment by alperaltuntas** [comment]
@mvertens, I am still trying to pinpoint the source of performance slowdown. It looks like the performance was degraded even before we switched to dev/unified. I am trying to pinpoint the culprit PR that was submitted to dev/ncar. As for this PR, I think there are no issues, so I am approving.

**Review by alperaltuntas — APPROVED** [review]

**Comment by mvertens** [comment]
@alperaltuntas - thanks for the update and for approving the PR. Please keep me posted on the performance issue.

**Pull request merged**
